### ISSUE TITLE
Youtube Screenshot

### ISSUE THREAD

**Issue by unicodeveloper** [goodheads/yourtube#1]
<img width="1119" alt="screen shot 2016-06-01 at 4 37 06 am" src="https://cloud.githubusercontent.com/assets/2946769/15697722/d7bba0ee-27b4-11e6-8b66-af3b516a3049.png">

**Comment by oguching** [comment]
why is this an issue?

**Comment by unicodeveloper** [comment]
Lool, I use github to store the images I use on [goodheads.io](http://goodheads.io). I'll close it anytime soon
