### ISSUE TITLE
server error when registering a new user: TypeError: Cannot read property '_id' of undefined

### ISSUE THREAD

**Issue by Boojio69** [goodheads/yourtube#14]
I keep getting this error: "User validation failed"

Desktop/yourtube/yourtube/config/token.js:12
    sub: user._id,
             ^

TypeError: Cannot read property '_id' of undefined

Any idea what is wrong with the register function? Thanks

**Comment by unicodeveloper** [comment]
A rough idea is that it's not getting the value of user, the user doesn't exist. Can you please compare it with the source code? Is this happening on the frontend(via the browser) or on the backend( via the terminal) ?

**Comment by Boojio69** [comment]
basically it's happening on testing the route with Postman after i downloaded the Yourtube folder and when I test the api's. all the api's work except the register user api. it gives me that error in terminal and in console it says: Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/api/register

Again I'm working directly on the code downloaded from here. Initially was trying to implement in my own project and was getting the same error. Then I downloaded the project to see how it works and was getting the same error...

**Comment by Boojio69** [comment]
Redownloaded again and now the register API works, sorry for issue report, yesterday it was literally driving me nuts, must've been something with my connection while downloading.

Thanks

**Comment by unicodeveloper** [comment]
You ran all the `bower and node install commands` and also created a .`.env` file in the root of the project?

**Comment by unicodeveloper** [comment]
OKAY COOL!..I'll close this issue then
