### ISSUE TITLE
Web page doesn't show any content

### ISSUE THREAD

**Issue by travis-r6s** [goodheads/yourtube#17]
I have seemingly successfully started the server, I downloaded the code from your GitHub project. but when i browse to the web page, it doesn't show any content (i have linked it to my cloudinary acc, and added media) or any of the login/signup pages?

![code](https://cloud.githubusercontent.com/assets/12587127/19493453/9136cf28-9572-11e6-963c-289c21ab125c.png)
![screenshot from 2016-10-18 20 35 20](https://cloud.githubusercontent.com/assets/12587127/19493454/913899ac-9572-11e6-8c8a-7af811d17815.png)

**Comment by unicodeveloper** [comment]
Please check the console to see the js error logs. Did you run `npm install` and `bower install` before starting the project? @thetre97

**Comment by travis-r6s** [comment]
yes, have run both of those commands - see below for console log.

![console](https://cloud.githubusercontent.com/assets/12587127/19497836/1733341e-9586-11e6-9534-d796d08af7c9.png)

**Comment by travis-r6s** [comment]
Tried it on my local machine - when i run nodemon server.js , it throws up this error..

![code from nodemon server_js](https://cloud.githubusercontent.com/assets/12587127/19498302/04fb74bc-9588-11e6-8a44-41c6247c58ee.png)

and npm start...
![npm start](https://cloud.githubusercontent.com/assets/12587127/19498334/37845f84-9588-11e6-8dd4-517692447f68.png)

**Comment by unicodeveloper** [comment]
Alright, you don't need to do a bower install, since the vendor folder is there already

**Comment by unicodeveloper** [comment]
Did your `npm install` finish installing all the nodejs modules?

**Comment by unicodeveloper** [comment]
Those angular errors are as a result of 3 files that are missing. I'm updating the repo as we speak. So you can pull the latest changes and try it again

**Comment by unicodeveloper** [comment]
I have fixed the errors now. Please pull again from the master branch to update the files on your local machine and then try again @thetre97

**Comment by travis-r6s** [comment]
thanks.. works fine now!
although, one thing, i have uploaded some .mp4 files to cloudinary, how do i get them to show up in yourtube?(i have changed the .env to my details)

**Comment by thetre97** [comment]
(i have changed the .env to my details)
