### ISSUE TITLE
No videos showing

### ISSUE THREAD

**Issue by travis-r6s** [goodheads/yourtube#18]
sorry, another issue :(

I have added my cloudinary details to the .env, and do have some videos stored in cloudinary, but they are not showing up on the homepage at all. also, when I try to upload something it just says 'processing...' and doesn't do anything...  my fault, or a problem with the code?

thanks,
![yt](https://cloud.githubusercontent.com/assets/12587127/19649894/66644f96-99ff-11e6-9fa4-a636c9e5958f.PNG)

**Comment by travis-r6s** [comment]
Home page
![yt_home](https://cloud.githubusercontent.com/assets/12587127/19649931/8681248e-99ff-11e6-9d61-f65e60b5248a.PNG)

**Comment by travis-r6s** [comment]
has just crashed as i was trying to upload something.

![crash](https://cloud.githubusercontent.com/assets/12587127/19649999/b308228c-99ff-11e6-9b7e-408bb0a53379.PNG)

**Comment by travis-r6s** [comment]
sorry - they HAVE uploaded to cloudinary, i can see them in the media library, but when i restart the app after it has crashed, still nothing shows up under 'home' or 'my videos'

**Comment by unicodeveloper** [comment]
It should show under 'my videos'. I'm surprised it's not showing. Are you
sure you have your right credentials set up?

_Best Regards,_

_Otemuyiwa Prosper_
_Technical Writer | Auth0  auth0.com https://auth0.com/_
_Google Developer Expert_
(c) +234-708-909-5645 | @unicodeveloper https://twitter.com/unicodeveloper |
prosper.otemuyiwa1 ( _Skype_ )
